// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhforoiinohzdccqdsuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoZm9yb2lpbm9oemRjY3Fkc3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODEwMDAsImV4cCI6MjA1OTg1NzAwMH0.72thWzNIkAkMaUmFjt07eW3IxD32ydGuDAnnuOizK9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);